sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.13.6
after_script: CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN bundle exec codeclimate-test-reporter
notifications:
  slack: $SLACK_CHANNEL_TOKEN
